name: deepblur
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-image
  - pip
  - pip:
      - torch==1.13.1
      - torchvision==0.13.1
      - datasets
      - huggingface_hub